//Here will be defined all element selectors
let basicAuthUserName = 'admin'
let basicAuthPassword = 'admin'
let mainUrl = 'https://the-internet.herokuapp.com/'
module.exports = {
    //basic Auth
    loginTextSelector: '//*[@id="content"]/div/p',
    loginTextCss: '#content > div > p',
    homePageUrl: 'https://the-internet.herokuapp.com/',
    basicAuthUrl: "https://" + basicAuthUserName + ":" + basicAuthPassword + "@" + "the-internet.herokuapp.com/basic_auth",
    expectedLoginText: 'Congratulations! You must have the proper credentials.',
    //Challenging DOM
    challengingDomWaitBeforeActions: '//*[@id="content"]/div/div/div/div[1]',
    challengingDomRegularExpression: "//*[contains(text(),'foo') or contains(text(),'bar') or contains(text(),'baz') or contains(text(),'qux')]",
    challengingDomUrl: mainUrl + 'challenging_dom',
    //Checkboxes
    checkboxUrl: mainUrl + 'checkboxes',
    firstCheckbox: '//*[@id="checkboxes"]/input[1]',
    secondCheckbox: '//*[@id="checkboxes"]/input[2]',
    //Disppearing elements
    disappearinElemUrl: mainUrl + 'disappearing_elements',
    disappearinElemHome: '//*[@id="content"]/div/ul/li[1]/a',
    disappearinElemAbout: '//*[@id="content"]/div/ul/li[2]/a',
    disappearinElemContactUs: '//*[@id="content"]/div/ul/li[3]/a',
    disappearinElemPortfolio: '//*[@id="content"]/div/ul/li[4]/a',
    //Dropdown menu
    dropdownUrl: mainUrl + 'dropdown',
    dropdownId: 'dropdown',
    option1css: '#dropdown>option[value=\'1\']',
    option2css: '#dropdown>option[value=\'2\']',
    //Dynamic Content
    dynamicContentUrl: mainUrl + 'dynamic_content?with_content=static',
    textReference: '//*[@id="content"]/div[3]/div[2]',
    refreshButton: '//*[@id="content"]/div/p[2]/a',
    //Dynamic elements
    dynamicElementsUrl: mainUrl + 'dynamic_controls',
    dynamicElementsCheckbox: 'input[type=\'checkbox\']',
    dynamicElementsRemoveCheckbox: '//*[@id="checkbox-example"]/button',
    dynamicElementsGoneMsg: '//*[@id="message"]',
    dynamicElementsInputBtn: '/html/body/div[2]/div/div[1]/form[2]/button',
    dynamicElementsEnableMsg: '/html/body/div[2]/div/div[1]/form[2]/p',
    dynamicElementsInputField: '//*[@id="input-example"]/input',
    //Dynamic loaded elements
    dynamicLoadingUrl: mainUrl + 'dynamic_loading',
    dynamicLoadingFirstLink: '//*[@id="content"]/div/a[1]',
    dynamicLoadingStartBtn: '//*[@id="start"]/button',
    dynamicLoadingFinishTextId: 'finish',
    dynamicLoadingSecondLink: '//*[@id="content"]/div/a[2]',
    //Entry Ad
    entryAdUrl: mainUrl + 'entry_ad',
    entryAdWindowTitle: '//*[@id="modal"]/div[2]/div[1]',
    entryAdWindowBody: '//*[@id="modal"]/div[2]/div[2]',
    entryAdWindowBodyText: "It's commonly used to encourage a user to take an action (e.g., give their e-mail address to sign up for something or disable their ad blocker).",
    entryAdCloseAlertBtnCss: '#modal > div.modal > div.modal-footer > p',
    entryAdCloseRestartPageCss: '#restart-ad',
    entryAdWindowTitleText: 'THIS IS A MODAL WINDOW',
    //Floating Menu
    floatingMenuUrl: mainUrl + 'floating_menu',
    floatingMenuBottomElement: '//*[@id="content"]/div/div[2]/div/p[6]',
    floatingMenuHomeBtn: '//*[@id="menu"]/ul/li[1]/a',
    floatingMenuNewsBtn: '//*[@id="menu"]/ul/li[2]/a',
    floatingMenuContactBtn: '//*[@id="menu"]/ul/li[3]/a',
    floatingMenuAboutBtn: '//*[@id="menu"]/ul/li[4]/a',
    //Login page
    loginPageUsernameKeys: 'tomsmith',
    loginPagePasswordkeys: 'SuperSecretPassword!',
    loginPageUrl: mainUrl + 'login',
    loginPageUsernameId: 'username',
    loginPagePasswordId: 'password',
    loginPageLoginBtn: '//*[@id="login"]/button',
    loginPageLoginMsg: '//*[@id="content"]/div/h2',
    loginPageLogoutBtn: '//*[@id="content"]/div/a',
    loginPageLogoutMsg: '//*[@id="content"]/div/h2',
    //Frames
    framesUrl: mainUrl + 'frames',
    framesFirstLink: '#content > div > ul > li:nth-child(1) > a',
    framesBottom: '/html/body',
    framesSecondLink: '//*[@id="content"]/div/ul/li[2]/a',
    framesInputWindowId: 'tinymce',
    //Slider
    sliderUrl: mainUrl + 'horizontal_slider',
    sliderInput: '//*[@id="content"]/div/div/input',
    sliderRange: '//*[@id="range"]',
    //Hovers
    hoversUrl: mainUrl + 'hovers',
    hoverUser1Img: '//*[@id="content"]/div/div[1]/img',
    hoverUser2Img: '//*[@id="content"]/div/div[2]/img',
    hoverUser3Img: '//*[@id="content"]/div/div[3]/img',
    hoverUser1Name: '/html/body/div[2]/div/div/div[1]/div/h5',
    hoverUser2Name: '/html/body/div[2]/div/div/div[2]/div/h5',
    hoverUser3Name: '/html/body/div[2]/div/div/div[3]/div/h5',
    //Inputs
    inputsUrl: mainUrl + 'inputs',
    inputsInputString: '//*[@id="content"]/div/div/div/input',
    //JQuery UI menu
    jqueryUrl: mainUrl + 'jqueryui/menu',
    jqueryEnable: '//*[@id="ui-id-3"]/a',
    jqueryDownloads: '//*[@id="ui-id-4"]/a',
    jqueryPdf: '//*[@id="ui-id-5"]/a',
    jqueryCsv: '//*[@id="ui-id-6"]/a',
    jqueryExcel: '//*[@id="ui-id-7"]/a',
    jqueryBackBtn: '//*[@id="ui-id-8"]/a',
    //jsAlerts
    alertsUrl: mainUrl + 'javascript_alerts',
    alertsFirstAlert: '/html/body/div[2]/div/div/ul/li[1]/button',
    alertsResult: '//*[@id="result"]',
    alertsSecondAlert: '//*[@id="content"]/div/ul/li[2]/button',
    alertsThirdAlert: '//*[@id="content"]/div/ul/li[3]/button',
    //key Presses
    keyPressesUrl: mainUrl + 'key_presses',
    keyPressesTarget: '//*[@id="target"]',
    keyPressesResult: '//*[@id="result"]',
    keyPressesBody: '/html/body',
    //large & deep DOM
    domUrl: mainUrl + 'large',
    domElement1: '//*[@id="sibling-17.3"]',
    domElement2: '//*[@id="sibling-30.3"]',
    domElement3: '//*[@id="sibling-50.3"]',
    domElement4: '//*[@id="large-table"]/tbody/tr[38]/td[1]',
    domElement5: '//*[@id="large-table"]/tbody/tr[50]/td[49]',
    //Redirection
    redirectionUrl: mainUrl + 'redirector',
    redirectionMainLink: '//*[@id="redirect"]',
    redirectionExpectedMainLinkUrl: 'https://the-internet.herokuapp.com/status_codes',
    redirection200Link: '//*[@id="content"]/div/ul/li[1]/a',
    redirectionStatusBody: '//*[@id="content"]/div/p',
    redirection301Link: '//*[@id="content"]/div/ul/li[2]/a',
    redirection404Link: '//*[@id="content"]/div/ul/li[3]/a',
    redirection500Link: '//*[@id="content"]/div/ul/li[4]/a',
    //ShadowDom
    shadowDomUrl: mainUrl + 'shadowdom',
    shadowDomSpanText: '//*[@id="content"]/my-paragraph[1]/span',
    shadowDomFirstLiText: '//*[@id="content"]/my-paragraph[2]/ul/li[1]',
    shadowDomSecondLiText: '//*[@id="content"]/my-paragraph[2]/ul/li[2]',
    //Shifting content
    shiftingUrl: mainUrl + 'shifting_content',
    shiftingFirstLink: '//*[@id="content"]/div/a[1]',
    shiftingMenuPixelShiftBtn: '//*[@id="content"]/div/p[3]/a',
    shiftingMenuHome: '//*[@id="content"]/div/ul/li[1]/a',
    shiftingMenuAbout: '//*[@id="content"]/div/ul/li[2]/a',
    shiftingMenuContact: '//*[@id="content"]/div/ul/li[3]/a',
    shiftingMenuPortfolio: '//*[@id="content"]/div/ul/li[4]/a',
    shiftingMenuGallery: '//*[@id="content"]/div/ul/li[5]/a',
    shiftingSecondLink: '//*[@id="content"]/div/a[2]',
    shiftingMenuRandomize: 'shifting_content/menu?mode=random&pixel_shift=100',
    shifringImageRandomize: mainUrl + 'shifting_content/image?mode=random',
    shiftingImagePixelShift: mainUrl + 'shifting_content/image?pixel_shift=100',
    shiftingImageRandomPixelShift: mainUrl + 'shifting_content/image?mode=random&pixel_shift=100',
    shiftingImageSimple: mainUrl + 'shifting_content/image?image_type=simple',
    shiftingThirdLink: '//*[@id="content"]/div/a[3]',
    shiftingTextSample: '//*[@id="content"]/div/div/div',
    //Typos
    typosUrl: mainUrl + 'typos',
    typosElementWithText: '//*[@id="content"]/div/p[2]',
    typosDefaultText: "Sometimes you'll see a typo, other times you won't.",
    typosNonDefaultText: "Sometimes you'll see a typo, other times you won,t.",
    //Editor
    editorUrl: mainUrl + 'tinymce',
    editorFrameId: 'mce_0_ifr',
    editorMainElementId: 'tinymce',
    editorBold: '//*[@id="content"]/div/div/div[1]/div[1]/div[2]/div/div[3]/button[1]',
    edtiorAlignCenter: '//*[@id="content"]/div/div/div[1]/div[1]/div[2]/div/div[4]/button[2]',
    editorItalic: '//*[@id="content"]/div/div/div[1]/div[1]/div[2]/div/div[3]/button[2]'

}
